
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const EngagementTracking = lazy(() => import("./pages/EngagementTracking.tsx"));
const LeadDetails = lazy(() => import("./pages/LeadDetails.tsx"));
const Leads = lazy(() => import("./pages/Leads.tsx"));
const Outreach = lazy(() => import("./pages/Outreach.tsx"));
const Reports = lazy(() => import("./pages/Reports.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/engagement-tracking", element: <EngagementTracking />},
	{ path: "/engagementtracking", element: <EngagementTracking />},
	{ path: "/lead-details", element: <LeadDetails />},
	{ path: "/leaddetails", element: <LeadDetails />},
	{ path: "/leads", element: <Leads />},
	{ path: "/outreach", element: <Outreach />},
	{ path: "/reports", element: <Reports />},
	{ path: "/settings", element: <Settings />},

];
